---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: ridoc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        envFrom:
        - configMapRef:
            name: env-${INDEX_NAME}

        image: ghcr.io/datalab-mi/ridoc-backend:${APP_VERSION}
        resources:
          requests:
            cpu: "0.1"
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 5000
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ridoc
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: backend
