---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: ridoc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - args:
        - "0"
        command:
        - ./start.sh
        envFrom:
        - configMapRef:
            name: env-${INDEX_NAME}
        env:
        - name: ES_HOST
          value: elasticsearch-master
        - name: "ELASTICSEARCH_USERNAME"
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: "ELASTICSEARCH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password          
        image: ghcr.io/datalab-mi/ridoc-backend:${APP_VERSION}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /usr/share/elasticsearch/data/extra
          name: extras
        - mountPath: /usr/share/elasticsearch/config/certs
          name: elasticsearch-certs
          readOnly: true
        resources:
          requests:
            cpu: "0.1"
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 5000
          name: http
      - name: tika
        image: logicalspark/docker-tikaserver
        ports:
        - containerPort: 9998
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: extras
        persistentVolumeClaim:
          claimName: extras
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          secretName: elasticsearch-master-certs      

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ridoc
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: backend
