---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: ridoc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - args:
        - "0"
        command:
        - ./start.sh
        envFrom:
        - configMapRef:
            name: env-${INDEX_NAME}
        env:
        - name: ES_HOST
          value: elasticsearch-master.elastic-stack
        image: ghcr.io/datalab-mi/ridoc-backend:${APP_VERSION}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /usr/share/elasticsearch/data/extra
          name: extras
        resources:
          requests:
            cpu: "0.1"
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 5000
          name: http
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: extras
        persistentVolumeClaim:
          claimName: extras     

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ridoc
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: backend
