apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: ridoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/datalab-mi/ridoc-frontend:${APP_VERSION}  
        imagePullPolicy: Always
        ports:
        - name: node
          containerPort: 3000
        env:
        - name: APP_VERSION
          value: ${APP_VERSION}  
        envFrom:
        - configMapRef:
            name: env-${INDEX_NAME}
        volumeMounts:
        - name: static-user
          mountPath: "/app/static/user"
          readOnly: true
      volumes:
      - name: static-user
        configMap:
          name: static-${INDEX_NAME}
---

kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: ridoc
spec:
  selector:
    app: frontend
  ports:
  - name: node
    port: 3000
    targetPort: 3000
