apiVersion: v1
kind: Namespace
metadata:
  name: ridoc

---

kind: Namespace
apiVersion: v1
metadata:
  name: traefik
  labels:
    name: traefik

---

kind: Namespace
apiVersion: v1
metadata:
  name: elastic-stack
  labels:
    name: elastic-stack