version: '3.4'
services:
  nginx-dev:
    image: nginx-dev
    container_name: nginx-dev
    build:
      context: ${NGINX}
      target: development
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        VIEWERJS_VERSION: ${VIEWERJS_VERSION}
    environment:
      - APP
      - ES_PROXY_PATH
      - ES_HOST
      - ES_INDEX
      - ES_PORT
      - BACKEND_HOST
      - BACKEND_PORT
      - FRONTEND_DEV_HOST
      - FRONTEND_PORT
      - PORT
      - KIBANA_PORT
      - KIBANA_HOST
      - LOGSTASH_HOST
    ports:
      - "$PORT:80"


networks:
  default:
    external:
      name: ${DC_NETWORK}
