version: '3.4'

services:
  backend:
    build:
      context: ${BACKEND}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    image: ${BACKEND_HOST}:${APP_VERSION}
    container_name: ${BACKEND_HOST}
    volumes:
      - ${BACKEND}/:/app/
      - ${DATA_PATH}:/data/user
      - ${ES_DATA}/extra:/usr/share/elasticsearch/data/extra
    expose:
      - "${BACKEND_PORT}"
    entrypoint: ./start.sh ${FLASK_DEBUG}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    env_file:
      - ${ENV_FILE}
    logging:
      #driver: none
      options:
        max-size: "10m"
        max-file: "1"
  tika:
    image: logicalspark/docker-tikaserver
    container_name: tika
    expose:
      - "9998"
    ports:
      - "1212:9998"
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    logging:
      driver: none


networks:
  default:
    external:
      name: ${DC_NETWORK}
