version: '3.4'
services:
  frontend-dev:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: dev
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        VIEWERJS_VERSION: ${VIEWERJS_VERSION}
    stdin_open: true
    environment:
      - NODE_ENV=development
      - SKIP_PREFLIGHT_CHECK=true
    image: ${FRONTEND_DEV_HOST}
    container_name: ${FRONTEND_DEV_HOST}
    volumes:
      - ${FRONTEND}/src:/app/src
      - ${FRONTEND}/static:/app/static
      - ${FRONTEND_STATIC_USER}:/app/static/user
    ports:
      - "${FRONTEND_PORT}:3000"
      - "35729:35729"
      - "3572:3572"
      - "10000:10000"

    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - APP_VERSION=${APP_VERSION}

    env_file:
      - $ENV_FILE

networks:
  default:
    external:
      name: ${DC_NETWORK}
