name: basic-test-backend

on: 
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          cp artifacts.sample artifacts
          make backend-dev
          make elasticsearch
      - name: test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 0
        run: make test
